name: Laravel CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ADMIN_PASSWORD: ${{ secrets.MYSQL_ADMIN_PASSWORD }}
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy .env
        run: |
          cp api/.env.example api/.env
          echo "DB_HOST=127.0.0.1" >> api/.env

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3.2"
          extensions: mbstring, xml, ctype, json, bcmath, curl
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: api

      - name: Generate key
        run: php artisan key:generate
        working-directory: api

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: api

      - name: Run Migrations
        run: php artisan migrate --force
        working-directory: api

      - name: Execute Tests
        run: php artisan test
        working-directory: api

      - name: Check Coding Standards
        run: ./vendor/bin/phpcs --standard=PSR12 app/
        working-directory: api
